# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:57:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import RootModel


class DataAvailability(RootModel[Any]):
    root: Any


class DataConstraints(RootModel[Any]):
    root: Any


class DataValues(RootModel[Any]):
    root: Any


class EntityLookup(RootModel[Any]):
    root: Any


class EntityRelationships(RootModel[Any]):
    root: Any


class MapCreation(RootModel[Any]):
    root: Any


class SearchDatasets(RootModel[Any]):
    root: Any


class SearchQuestions(RootModel[Any]):
    root: Any


class Suggestions(RootModel[Any]):
    root: Any


class Format(Enum):
    google = 'google'


class Relation(Enum):
    parent = 'parent'
    child = 'child'
    sibling = 'sibling'
    peer = 'peer'


class Type(Enum):
    entity = 'entity'
    category = 'category'
    publisher = 'publisher'
    dataset = 'dataset'
    question = 'question'
